aws_images/albums/urls.py
from django.urls import path
from .views import create
from .views import AlbumListView
from .views import AlbumDetailView

app_name = 'albums'

urlpatterns = [
    path('', AlbumListView.as_view(), name='list'),
    path('create/', create, name="create"),
    path('<int:pk>/detail', AlbumDetailView.as_view(), name="detail"),
]

aws_images/aws_images/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('albums/', include('albums.urls')),
    path('images/', include('images.urls'))
]

aws_images/images/urls.py
from django.urls import path
from .views import create
from .views import update
from .views import show
from .views import delete
from .views import download
from .views import delete_many
from .views import download_many
from .views import search

app_name = 'images'

urlpatterns = [
    path('create/', create, name="create"),
    path('update/<int:pk>/', update, name="update"),
    path('show/<int:pk>/', show, name="show"),
    path('delete/<int:pk>/', delete, name="delete"),
    path('download/<int:pk>/', download, name="download"),
    path('delete/many', delete_many, name="delete_many"),
    path('download/many', download_many, name="download_many"),
    path('search', search, name="search")
]

aws_images/images/models.py
import zipfile
from io import BytesIO

from django.db import models
from django.http import HttpResponse
from albums.models import Album
from AWS import rename_file
from AWS import delete_file
from AWS import get_mediafile_content


class ImageManager(models.Manager):

    def delete_by_aws(self, id):
        image = self.filter(id=id).first()

        if image and delete_file(image.bucket, image.key):
            image.delete()
            return id

    def download_and_zip(self, ids):
        zip_io = BytesIO()
        with zipfile.ZipFile(zip_io, mode='w', compression=zipfile.ZIP_DEFLATED) as zip_writter:
            for id in ids:
                image = self.filter(id=id).first()
                data = get_mediafile_content(image.bucket, image.key)
                if image and data:
                    zip_writter.writestr(image.name, data)
                         
        return zip_io

class Image(models.Model):
    key = models.CharField(max_length=100, null=False, blank=False)
    bucket = models.CharField(max_length=100, null=False, blank=False)
    name = models.CharField(max_length=50, null=False, blank=False)
    content_type = models.CharField(max_length=20, null=False, blank=False)
    size = models.IntegerField()
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    create_at = models.DateTimeField(auto_now_add=True)

    objects = ImageManager()

    def __str__(self):
        return self.name

    @property
    def url(self):
        return f"https://{self.bucket}.s3.amazonaws.com/{self.key}"

    @property
    def title(self):
        return self.name.split(".")[0] if "." in self.name else self.name

    @property
    def extension(self):
        return self.name.split(".")[-1] if "." in self.name else ""

    def set_name(self, value):
        """set a new name"""
        name = f"{value}.{self.extension}" if self.extension else value
        key = f"{self.album.key}{name}"

        if rename_file(bucket=self.bucket, new_mediafile_key=key, old_mediafile_key=self.key):
            self.key = key
            self.name = name
            self.save()

    def delete_image(self):
        """delete the image from the data base and from AWS"""
        if delete_file(bucket=self.bucket, key=self.key):
            print(f"Deleting image {self.name}")
            self.delete()
            return True
        print(f"Deletion was unsuccessful for image {self.name}")
        

aws_images/images/forms.py
from django import forms

class UploadFileForm(forms.Form):
    album_id = forms.CharField(required=True, widget=forms.HiddenInput())
    file = forms.FileField(required=True,
                           label='Imagen',
                           widget=forms.FileInput(attrs={"accept": "image/*"}))

    def __init__(self, *args, **kwargs):
        super(UploadFileForm, self).__init__(*args, **kwargs)

        # Se define el estilo del selector de archivos
        self.fields["file"].widget.attrs["class"] = 'form-control-file'

aws_images/images/views.py
import json
import shutil
import os

from pathlib import Path
from wsgiref.util import FileWrapper
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import get_template
from django.urls import reverse
from django.http import JsonResponse, HttpResponse
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt

from AWS import upload_image, get_mediafile_content, delete_file, download_file
from albums.models import Album
from .models import Image
from .forms import UploadFileForm

def update(request, pk):
    image = get_object_or_404(Image, pk=pk)

    if request.method == 'POST':
        new_name = request.POST.get('name', '')
        image.set_name(new_name)

    return JsonResponse({
        'id': image.id,
        'name': image.title,
        'url': image.url
    })

# Create your views here.
def create(request):
    if request.method == "POST":
        form = UploadFileForm(request.POST, request.FILES)

        if form.is_valid():
            file = form.cleaned_data['file']
            album = get_object_or_404(Album, id=form.cleaned_data["album_id"])
            key = f'{album.key}{file._name}'

            if upload_image(settings.BUCKET, key, file):
                image = Image.objects.create(name=file._name, 
                                             content_type=file.content_type, 
                                             size=file.size,
                                             bucket=settings.BUCKET,
                                             key=key,
                                             album=album)
            return redirect('albums:detail', album.id)

def show(request, pk):
    image = get_object_or_404(Image, pk=pk)
    return JsonResponse({
        'id': image.id,
        'name': image.name,
        'delete_url': reverse('images:delete', kwargs={"pk": image.id}),
    })

def delete(request, pk):
    """Delete an image"""
    image = get_object_or_404(Image, pk=pk)
    album = image.album
    Image.objects.delete_via_aws(image.id)
    return redirect('albums:detail', album.id)

def download(request, pk):
    image = get_object_or_404(Image, pk=pk)
    content = get_mediafile_content(image.bucket, image.key)
    response = HttpResponse(content, content_type=image.content_type)
    response['Content-Disposition'] = f"attachment; filename={image.name}"

    return response

@csrf_exempt
def delete_many(request):
    if request.method == "POST":
        payload = json.loads(request.body)
        ids = payload.get('ids', [])

        return JsonResponse({'ids': [Image.objects.delete_by_aws(id) for id in ids]})

@csrf_exempt
def download_many(request):
    temp_folder = 'tmp/images'
    Path(temp_folder).mkdir(parents=True, exist_ok=True)

    for id in request.GET.get('ids').split(','):
        image = Image.objects.filter(id=int(id)).first()

        if image:
            local_path = os.path.join(temp_folder, image.name)
            download_file(image.bucket, image.key, local_path)

    shutil.make_archive(temp_folder, 'zip', temp_folder)
    wrapper = FileWrapper(open('tmp/images.zip', 'rb'))

    response = HttpResponse(wrapper, content_type='application/zip')
    response["Content-Disposition"] = 'attachment; filename="images.zip"'

    return response

@csrf_exempt
def search(request):
    if request.method == "GET" and request.GET.get("q"):
        template = get_template('images/snippets/image.html')

        images = [template.render({'image': image}) 
                  for image in Image.objects.filter(name__startswith=request.GET["q"])]

        return JsonResponse({
            'success': True,
            'images': images
        })

aws_images/images/templates/images/snippets/delete.html
<div class="modal" tabindex="-1" id="deleteModal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Eliminar Imagen</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p>Desea elmininar <strong id='strong-name'></strong>?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
          <a href="" class="btn btn-danger" id="delete-modal-button">Eliminar</a>
        </div>
      </div>
    </div>
</div>

aws_images/images/templates/images/snippets/image.html
<tr class="row-image" image-id="{{ image.id }}">
    <td>
        <div>
            <input class="form-check-input check-images" type="checkbox" id="image-checkbox-{{ image.id }}" image-id="{{ image.id }}" value="">
        </div>
    </td>
    <td>
        <input type="hidden" value="{{ image.url }}" id="image-preview-{{ image.id }}">
        <div id="image-name-{{ image.id }}">
            {{ image.title }}
        </div>  
        <form action="{% url 'images:update' image.pk %}" method="POST" class="image-form" image-id="{{ image.id }}">
            {% csrf_token %}
            <input type="hidden" value="{{ image.title }}" class="form-control" id="image-input-name-{{ image.id }}" name="name">
        </form>
    </td>
    <td>{{ image.create_at }}</td>
    <td>{{ image.size }}</td>
    <td>
        <div class='btn-group'>
            <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown">
            </button>
            <div class="dropdown-menu">
                <a href="{{ image.url }}" target="_blank" class="dropdown-item">Vista Previa</a>
                <a href="" class="dropdown-item image-edit" image-id="{{ image.id }}">Editar</a>
                <a href="{% url 'images:download' image.id %}" class="dropdown-item">Descargar</a>
                <div class="dropdown-divider"></div>
                <a href="{% url 'images:show' image.id %}" data-bs-toggle="modal" data-bs-target="#deleteModal" class="dropdown-item image-delete" image-id="{{ image.id }}">Eliminar</a>
            </div>
        </div>
    </td>
</tr>

aws_images/images/templates/images/snippets/modal.html
<div class="modal fade" id="newImage" tabindex="-1" aria-labelledby="newAlbumLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="newAlbumLabel">Nuevo Imagen</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
            <form action="{% url 'images:create' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="modal-body">    
                    {% for field in form %}
                        <div class="form-group">
                            <p></p>
                            {{ field }}
                            <p></p>
                        </div>
                    {% endfor %}
        
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <input class='btn btn-primary' type='submit' value='Subir'>
                </div>
            </form>
        </div>
    </div>
</div>