aws_images/albums/urls.py
from django.urls import path
from .views import create
from .views import AlbumListView
from .views import AlbumDetailView

app_name = 'albums'

urlpatterns = [
    path('', AlbumListView.as_view(), name='list'),
    path('create/', create, name="create"),
    path('<int:pk>/detail', AlbumDetailView.as_view(), name="detail"),
]

aws_images/aws_images/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('albums/', include('albums.urls')),
    path('images/', include('images.urls'))
]

aws_images/albums/models.py
from django.db import models
from AWS import create_folder


class AlbumManager(models.Manager):

    def create_by_aws(self, bucket, title, description):
        key = create_folder(bucket, title.replace(' ', '').lower())
        if key:
            return self.create(title=title, description=description, 
                               bucket=bucket, key=key)
        return None


class Album(models.Model):
    """pass"""
    title = models.CharField(max_length=50, null=False, blank=False) # con null=False, blank=False se le de ha entnder a django que este campo es requerido
    description = models.TextField()
    bucket = models.CharField(max_length=100, null=False, blank=False) # Se usa para conocer la ruta exacta del bucket de S3
    key = models.CharField(max_length=50, null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True) # Agrega la fecha automaticamente

    objects = AlbumManager()

    def __str__(self):
        return self.title

    @property
    def images(self):
        return self.image_set.all()

aws_images/albums/forms.py
from django.forms import ModelForm
from .models import Album

class AlbumForm(ModelForm):
    """"""
    class Meta:
        model = Album
        fields = ['title', 'description']

    def __init__(self, *args, **kwargs):
        super(AlbumForm, self).__init__(*args, **kwargs)

        self.fields['title'].widget.attrs.update({
            'class': 'form-control',
            'id': 'title',
            'placeholder': 'Título'
        })
        self.fields['description'].widget.attrs.update({
            'class': 'form-control',
            'id': 'description',
            'placeholder': 'Descripción'
        })

aws_images/albums/views.py
from django.shortcuts import render, redirect
from django.views.generic import DetailView
from django.views.generic import ListView
from django.conf import settings

from .models import Album
from .forms import AlbumForm

from images.forms import UploadFileForm


class AlbumDetailView(DetailView):
    model = Album
    template_name = 'albums/detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['title'] = self.get_object().title
        context['images'] = self.get_object().images
        context['form'] = UploadFileForm({
            'album_id': self.get_object().id
        })

        return context

class AlbumListView(ListView):
    model = Album
    template_name = 'albums/list.html'
    paginate_by = 10

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['title'] = 'Galeria'
        context['form'] = AlbumForm()

        return context

def create(request):
    form = AlbumForm(request.POST or None)

    if request.method == 'POST' and form.is_valid():
        # album = form.save()
        album = Album.objects.create_by_aws(bucket=settings.BUCKET,
                                            title=form.cleaned_data["title"],
                                            description=form.cleaned_data["description"])

        return redirect('albums:list')

# def list(request):
#     form = AlbumForm()
#     albums = Album.objects.all()
#     context = {
#         'title': 'Galeria',
#         'form': form,
#         'albums': albums
#     }
#     return render(request, 'albums/list.html', context)

aws_images/albums/templates/albums/snippets/modal.html
<div class="modal fade" id="newAlbum" tabindex="-1" aria-labelledby="newAlbumLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="newAlbumLabel">Nuevo Album</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
            <form action="{% url 'albums:create' %}" method="POST">
                {% csrf_token %}
                <div class="modal-body">    
                    {% for field in form %}
                        <div class="form-group">
                            <p></p>
                            {{ field }}
                            <p></p>
                        </div>
                    {% endfor %}
        
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <input class='btn btn-primary' type='submit' value="Crear">
                </div>
            </form>
        </div>
    </div>
</div>