aws_images/albums/urls.py
from django.urls import path
from .views import create
from .views import AlbumListView
from .views import AlbumDetailView

app_name = 'albums'

urlpatterns = [
    path('', AlbumListView.as_view(), name='list'),
    path('create/', create, name="create"),
    path('<int:pk>/detail', AlbumDetailView.as_view(), name="detail"),
]

aws_images/aws_images/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('albums/', include('albums.urls')),
    path('images/', include('images.urls'))
]

aws_images/images/urls.py
from django.urls import path
from .views import create
from .views import update
from .views import show
from .views import delete
from .views import download
from .views import delete_many
from .views import download_many
from .views import search

app_name = 'images'

urlpatterns = [
    path('create/', create, name="create"),
    path('update/<int:pk>/', update, name="update"),
    path('show/<int:pk>/', show, name="show"),
    path('delete/<int:pk>/', delete, name="delete"),
    path('download/<int:pk>/', download, name="download"),
    path('delete/many', delete_many, name="delete_many"),
    path('download/many', download_many, name="download_many"),
    path('search', search, name="search")
]

aws_images/albums/models.py
from django.db import models
from AWS import create_folder


class AlbumManager(models.Manager):

    def create_by_aws(self, bucket, title, description):
        key = create_folder(bucket, title.replace(' ', '').lower())
        if key:
            return self.create(title=title, description=description, 
                               bucket=bucket, key=key)
        return None


class Album(models.Model):
    """pass"""
    title = models.CharField(max_length=50, null=False, blank=False) # con null=False, blank=False se le de ha entnder a django que este campo es requerido
    description = models.TextField()
    bucket = models.CharField(max_length=100, null=False, blank=False) # Se usa para conocer la ruta exacta del bucket de S3
    key = models.CharField(max_length=50, null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True) # Agrega la fecha automaticamente

    objects = AlbumManager()

    def __str__(self):
        return self.title

    @property
    def images(self):
        return self.image_set.all()

aws_images/albums/forms.py
from django.forms import ModelForm
from .models import Album

class AlbumForm(ModelForm):
    """"""
    class Meta:
        model = Album
        fields = ['title', 'description']

    def __init__(self, *args, **kwargs):
        super(AlbumForm, self).__init__(*args, **kwargs)

        self.fields['title'].widget.attrs.update({
            'class': 'form-control',
            'id': 'title',
            'placeholder': 'Título'
        })
        self.fields['description'].widget.attrs.update({
            'class': 'form-control',
            'id': 'description',
            'placeholder': 'Descripción'
        })

aws_images/albums/views.py
from django.shortcuts import render, redirect
from django.views.generic import DetailView
from django.views.generic import ListView
from django.conf import settings

from .models import Album
from .forms import AlbumForm

from images.forms import UploadFileForm


class AlbumDetailView(DetailView):
    model = Album
    template_name = 'albums/detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['title'] = self.get_object().title
        context['images'] = self.get_object().images
        context['form'] = UploadFileForm({
            'album_id': self.get_object().id
        })

        return context

class AlbumListView(ListView):
    model = Album
    template_name = 'albums/list.html'
    paginate_by = 10

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['title'] = 'Galeria'
        context['form'] = AlbumForm()

        return context

def create(request):
    form = AlbumForm(request.POST or None)

    if request.method == 'POST' and form.is_valid():
        # album = form.save()
        album = Album.objects.create_by_aws(bucket=settings.BUCKET,
                                            title=form.cleaned_data["title"],
                                            description=form.cleaned_data["description"])

        return redirect('albums:list')

# def list(request):
#     form = AlbumForm()
#     albums = Album.objects.all()
#     context = {
#         'title': 'Galeria',
#         'form': form,
#         'albums': albums
#     }
#     return render(request, 'albums/list.html', context)

aws_images/albums/templates/albums/detail.html
{% extends 'base/base.html' %}

<!--  ayuda a seleccionar la fila -->
{% block style %}
<style>
    .row-image {
        cursor: pointer;
    }
</style>
{% endblock %}

{% block content %}
{% include 'images/snippets/modal.html' %}
{% include 'images/snippets/delete.html' %}

<div class="row">
    <div class="col">
        <h4><a href="{% url 'albums:list' %}">Galeria</a> / {{ object }}</h4>
    </div>
</div>

<div class="row mt-2">
    <div class="col">
        <form action="{% url 'images:search' %}" id="image-search">
            <input type="text" class="form-control" name="q" placeholder="Escriba una busqueda">
        </form>
    </div>
</div>

<hr>

<div class="row">
    <div class="col">
        <button type="button" class="btn btn-primary me-md-2" data-bs-toggle="modal" data-bs-target="#newImage">
            Nueva Imagen
        </button>
        <a type="button" href="{% url 'images:download_many' %}" class="btn btn-info me-md-2 disabled" id="downloadImagesButton">
            Descargar
        </a>
        <a type="button" href="{% url 'images:delete_many' %}" class="btn btn-danger me-md-2 disabled" id="deleteImagesButton">
            Eliminar
        </a>
    </div>
</div>

<div class='row mt-2'>
    <div class='col-8'>
        <table class='table'>
            <thead>
                <tr>
                    <th>
                        <div>
                            <input class="form-check-input" type="checkbox" id="check-all-images" value="">
                        </div>
                    </th>
                    <th>Nombre</th>
                    <th>Fecha Creacion</th>
                    <th>Size</th>
                    <th></th>
                </tr>
            </thead>
            <tbody id="table-images">
                {% for image in images %}
                    {% include 'images/snippets/image.html' %}
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class='col-4'>
        <img src="{{ input }}" alt="" width="300" height="300" id=image-preview>
    </div>
</div>

{% endblock %}

{% block javascript %}
<script>
    const imagePreview = document.getElementById('image-preview');
    const imageDefault = "https://djangobucketcurso.s3.us-east-2.amazonaws.com/istockphoto-922962354-612x612.jpg";
    const checkAllImages = document.getElementById('check-all-images');
    const downloadImages = document.getElementById('downloadImagesButton');
    const deleteImages = document.getElementById('deleteImagesButton');
    const imageSearch = document.getElementById('image-search');

    function checkInputs(){
        var images = document.querySelectorAll('input.check-images[type="checkbox"]:checked');
        if (images.length >= 2){
            downloadImages.classList.remove('disabled');
            deleteImages.classList.remove('disabled');
        } else {
            downloadImages.classList.add('disabled');
            deleteImages.classList.add('disabled');
        }
    }

    function selectRow(row){
        var imageId = row.getAttribute('image-id');
        var input = document.getElementById('image-preview-' + imageId);
        imagePreview.src = input.value

        // elminina la  clase table-active 
        document.querySelectorAll('.table-active').forEach(element => {
            element.classList.remove('table-active');
        })

        row.classList.add('table-active');
    }

    function setDefaultImage(){
        var rows = document.getElementsByTagName('tr');
        if (rows.length >=2 ){
            selectRow(rows[1]);
        } else {
            imagePreview.src = imageDefault;
        }
    }

    function getSelectedImages(){
        var ids = [];
        document.querySelectorAll('input.check-images[type="checkbox"]:checked').forEach(element => {
            var imageId = element.getAttribute('image-id');
            ids.push(imageId);
        })
        return ids;
    };

    function registerEvents(){

        document.querySelectorAll('.check-images').forEach(element => {
            element.addEventListener('change', function(event){
                checkInputs();
            })
        });

        document.querySelectorAll('.row-image').forEach(element => {
            element.addEventListener('click', function(event){
                selectRow(this);
            })
        })

        document.querySelectorAll('.image-edit').forEach(element => {
            element.addEventListener('click', function(event){
                event.preventDefault();
                var imageId = this.getAttribute('image-id');
                var input = document.getElementById('image-input-name-' + imageId);
                var div = document.getElementById('image-name-' + imageId)
                div.style.display = 'none';
                input.setAttribute('type', 'text');
            })
        })
        
        document.querySelectorAll('.image-form').forEach(element => {
            element.addEventListener('submit', function(event){
                event.preventDefault();

                // Se crea la peticion de forma asincrona el parametro action contiene el url al que se apunta esta peticion
                fetch(this.action, {
                    body: new FormData(this),
                    method: 'POST'
                })
                .then(response => response.json())
                .then(data => {

                    // obtiene el imageId del formulario
                    var imageId = this.getAttribute('image-id');

                    // busca de nuevo el bloque de input y lo esconde
                    var input = document.getElementById('image-input-name-' + imageId);
                    input.value = data.name;
                    input.setAttribute('type', 'hidden');

                    // asigna el nuevo valor al label que lleva el nombre de la imagen
                    var div = document.getElementById('image-name-' + imageId);
                    div.innerHTML = data.name;
                    div.style.display = 'block';

                    // actualiza la direccion de url del preview de la imagen
                    var preview = document.getElementById('image-preview-' + imageId);
                    preview.value = data.url;

                })
            })
        })

    };

    document.querySelectorAll('.image-delete').forEach(element => {
        element.addEventListener('click', function(event){
            event.preventDefault();
            var imageId = this.getAttribute('image-id');
        })
    })

    var deleteModal = document.getElementById('deleteModal')
    deleteModal.addEventListener('show.bs.modal', function (event) {
    // Button that triggered the modal
        var button = event.relatedTarget;
        fetch(button.href)
        .then(response => response.json())
        .then(function(data){
            var imageName = deleteModal.querySelector('#strong-name');
            imageName.textContent = data.name;
            var deleteButton = deleteModal.querySelector('#delete-modal-button');
            deleteButton.setAttribute('href', data.delete_url);
            
        });
    })

    checkAllImages.addEventListener('change', function(event){
        document.querySelectorAll('.check-images').forEach(element => {
            element.checked = this.checked;
        })
        checkInputs();
    });

    deleteImages.addEventListener('click', function(event){
        event.preventDefault();
        var ids = getSelectedImages();

        fetch(this.href, {
            method: "POST",
            body: JSON.stringify({'ids': ids})
        })
        .then(response => response.json())
        .then(function(data){
            for(var i=0; i < data.ids.length; i++){
                var imageId = data.ids[i];
                document.querySelector('tr.row-image[image-id="' + imageId + '"]').remove();
            }
            setDefaultImage();
        });
    });

    downloadImages.addEventListener('click', function(event){
        event.preventDefault();
        var ids = getSelectedImages();

        window.location.href = this.href + '?ids=' + ids;
    });

    imageSearch.addEventListener('submit', function(event){
        event.preventDefault();

        fetch(this.action + '?q=' + this.q.value)
        .then(response => response.json())
        .then(data => {
            var table = document.getElementById('table-images');
            table.innerHTML = data.images.toString().replaceAll(',','');
        });

        registerEvents();
        setDefaultImage();

    });

    registerEvents();
    setDefaultImage();

</script>
{% endblock %}

aws_images/albums/templates/albums/list.html
{% extends 'base/base.html' %}

{% block content %}
{% include 'albums/snippets/modal.html' %}

<div class="row mt-4">
    <div class="col-10">
        <h2>Galeria</h2>
    </div>

    <div class="col justify-content-md-end">
        <button type="button" class="btn btn-outline-primary me-md-2" data-bs-toggle="modal" data-bs-target="#newAlbum">
            Nuevo Album
        </button>
    </div>
</div>

<div class="row">
    <div class="col">
        <table class="table table-dark table-striped">
            <thead>
                <tr>
                    <th scope='col'>Título</th>
                    <th scope='col'>Fecha de Creación</th>
                    <th scope='col'>Descripción</th>
                </tr>
            </thead>
            <tbody>
                {% for album in object_list %}
                    <tr>
                        <td><i class="fas fa-folder" color="#111111"></i>
                            <a href="{% url 'albums:detail' album.id %}">
                                {{ album.title }}
                            </a>
                        </td>
                        <td>{{ album.created_at | date:'d M Y'}}</td>
                        <td>{{ album.description }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>


{% endblock %}